export default {

      en: {
          Home: 'Home',
          Help: "Help",
          Feed: "Feedback",
          Contri: "Contribute",
          Mobile: "Mobile",
          Dev: "Developers",
          Langs: "Languages",
          placeholder: "Search Anything...",
          Quick: "Quick Links",
          All: "All",
          Makki: "Makki Surahs of Quran",
          Madni: "Madini Surahs of Quran",
          Manzil: "Manzil",
            SurahYasin: "Surah Yasin (Yaseen)",
            SurahArRahman: "Surah Ar-Rahman",
            SurahAlMulk: "Surah Al Mulk",
            AyatulKursi: "Ayatul Kursi",
          Site:"Site",
          Prayer:"Prayer times",
          About:"About Us",
          Contact:"Contact Us",
          Footertext:"Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
          FootCopy:"2019 Al-Kitaab.com. All rights reserved."},
      
        de: {
      
            Home: 'Home',
          Help: "Helpen",
          Feed: "terugkoppeling",
          Contri: "Bijdragen",
          Mobile: "mobiel",
          Dev: "Developers",
          Langs: "talen",
          placeholder: "Alles zoeken ...",
          Quick: "Snelle links",
          All: "Allemaal",
          Makki: "Makki Surahs van Koran",
          Madni: "Madini Surahs van Koran",
          Manzil: "Manzil",
            SurahYasin: "Surah Yasin (Yaseen)",
            SurahArRahman: "Surah Ar-Rahman",
            SurahAlMulk: "Surah Al Mulk",
            AyatulKursi: "Ayatul Kursi",
          Site: "plaats",
          Prayer: "Gebedstijden",
          About: "Over Ons",
          Contact: "Contact Ons",
          Footertext: "Al-kitaab.com (ook bekend als de nobele koran, al koran, heilige koran, koran) is een pro bono-project.",
          FootCopy: "2019 Al-Kitaab.com. Alle rechten voorbehouden."},
            
      indo:  {
            Home: 'Home',
          Help: "Membantu",
          Feed: "Umpan balik",
          Contri: "Menyumbang",
          Mobile: "Mobile",
          Dev: "Pengembang",
          Langs: "Bahasa",
          placeholder: "Cari Apa Saja ...",
          Quick: "tautan langsung",
          All: "Semua",
          Makki: "Makki Surahs of Quran",
          Madni: "Madini Surahs of Quran",
          Manzil: "Manzil",
            SurahYasin: "Surah Yasin (Yaseen)",
            SurahArRahman: "Surah Ar-Rahman",
            SurahAlMulk: "Surah Al Mulk",
            AyatulKursi: "Ayatul Kursi",
          Site: "tempat terletak",
          Prayer: "Waktu sholat",
          About: "Tentang kami",
          Contact: "Hubungi kami",
          Footertext: "Al-kitaab.com (juga dikenal sebagai quran mulia, al quran, quran suci, koran) adalah proyek pro bono.",
          FootCopy: "2019 Al-Kitaab.com. Seluruh hak cipta."},
            
      ar:   {   
       
            Islam: 'الاسلام',
          Help: "مساعدة",
          Feed: "ردود الفعل",
          Contri: "تساهم",
          Mobile: "التليفون المحمول",
          Dev: "المطورون",
          Langs: "اللغات",
          placeholder: "البحث في أي شيء ...",
          Quick: "روابط سريعة",
          All: "الكل",
          Makki: "سورة مكي من القرآن",
          Madni: "سورة مديني القرآنية",
          Manzil: "المنزل",
            SurahYasin: "سورة ياسين (ياسين)",
            SurahArRahman: "سورة الرحمن",
            SurahAlMulk: "سورة الملك",
            AyatulKursi: "آية الكرسي",
          Site :"موقع",
          Prayer: "أوقات الصلاة",
          About: "معلومات عنا",
          Contact :"اتصل بنا",
          Footertext: ".(المعروف أيضًا باسم القرآن الكريم ، القرآن ، القرآن الكريم ، القرآن) هو مشروع مجاني Al- Kitaab.com",
          FootCopy: "2019 كتاب. كل الحقوق محفوظة."},
                  
       tr:   {
            Islam: 'İslâm',
          Help: "yardım et",
          Feed: "geri bildirim",
          Contri: "Katkıda bulunmak",
          Mobile: "seyyar",
          Dev: "Geliştiriciler",
          Langs: "duujjil",
          placeholder: "Her şeyi ara ...",
          Quick: "Hızlı Linkler",
          All: "Herşey",
          Makki: "Makki Surahs of Quran",
          Madni: "Madini Surahs of Quran",
          Manzil: "Manzil",
            SurahYasin: "Surah Yasin (Yaseen)",
            SurahArRahman: "Surah Ar-Rahman",
            SurahAlMulk: "Surah Al Mulk",
            AyatulKursi: "Ayatul Kursi",
          Site: "yer",
          Prayer: "İbadet zamanları",
          About: "Hakkımızda",
          Contact: "Bizimle iletişime geçin",
          Footertext: "Alkitaab.com (asil Kur'an, Al Kur'an, Kur'an-ı Kerim olarak da bilinir) yanlısı bir bono projesidir.",
          FootCopy: "2019 Al-Kitaab.com. Tüm hakları Saklıdır."},
      
      fr:   {
         Home: 'Home',
          Help: "Aidez-moi",
          Feed: "Retour d'information",
          Contri: "Contribuer",
          Mobile: "Mobile",
          Dev: "Développeurs",
          Langs: "Langages",
          placeholder: "Rechercher n'importe quoi ...",
          Quick: "Liens rapides",
          All: "Tout",
          Makki: "Makki Sourates du Coran",
          Madni: "Madini Sourates du Coran",
          Manzil: "Manzil",
            SurahYasin: "Surah Yasin (Yaseen)",
            SurahArRahman: "Surah Ar-Rahman",
            SurahAlMulk: "Surah Al Mulk",
            AyatulKursi: "Ayatul Kursi",
          Site: "Site",
          Prayer: "Temps de prière",
          About: "À propos de nous",
          Contact: "Contactez nous",
          Footertext: "Al-kitaab.com (également connu sous le nom de noble coran, al coran, saint coran, coran) est un projet bénévole.",
          FootCopy: "2019 Al-Kitaab.com. Tous les droits sont réservés."},
      
       ur:   {
       
         Islam: 'اسلام',
          Help: "مدد",
          Feed: "آراء",
          Contri: "تعاون کریں",
          Mobile: "موبائل",
          Dev: "ڈویلپرز",
          Langs: "زبانیں",
          placeholder: "…کچھ بھی تلاش کریں",
          Quick: "فوری روابط",
          All: "سب",
          Makki: "قرآن کی مکی سورتیں",
          Madni: "قرآن کی مدینی سورتیں",
          Manzil: "منزل",
            SurahYasin: "سورة ياسين (ياسين)",
            SurahArRahman: "سورة الرحمن",
            SurahAlMulk: "سورة الملك",
            AyatulKursi: "آية الكرسي",
          Site: "سائٹ",
          Prayer: "نماز کے اوقات",
          About: "ہمارے بارے میں",
          Contact: "ہم سے رابطہ کریں",
          Footertext: "Al-kitaab.com(بطور نوبل قرآن ، القرآن ، قرآن پاک ، کوران بھی کہا جاتا ہے) ایک بنو پروجیکٹ ہے۔",
          FootCopy: "2019 Al-Kitaab.com. جملہ حقوق محفوظ ہیں."},
        
        };
      